close all;
clear,clc;
inImg = 'gdut_01.jpg';
f1 = ImgDilate(inImg,'diamond');
f2 = ImgDilate(inImg,'disk');
f3 = ImgDilate(inImg,'octagon');
figure(1),imshow(inImg),title('输入图像');
figure(2),imshow(f1),title('菱形结构元素膨胀');
figure(3),imshow(f2),title('圆盘结构元素膨胀');
figure(4),imshow(f3),title('八边形结构元素膨胀');